// <auto-generated />
using ConsoleClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleClient.Migrations
{
    [DbContext(typeof(PassTimeContext))]
    partial class PassTimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Domain.PassTimeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNr")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PassTime");
                });
#pragma warning restore 612, 618
        }
    }
}
