stages:
    - build
    - deploy

# As default cache policy, cache all untracked files per job and branch (Gradle distributions, Node modules etc)
cache:
    key: "$CI_JOB_NAME $CI_COMMIT_REF_NAME"
    paths:
        - Tools\*

build:
    stage: build
    script:
        - powershell -File build.ps1 -target=DefaultCi
    artifacts:
        paths:
            - .\build\*.*

deploy.develop:
    stage: deploy
    dependencies:
        - build
    script:
        - nuget.exe push .\build\*.nupkg -Source http://nexus.flexlink.se/repository/nuget-hosted-prerelease/ -ApiKey %NUGET_API_KEY%
    only:
        - develop


deploy.release:
    stage: deploy
    dependencies:
        - build
    script:
        - nuget.exe push .\build\*.nupkg -Source http://nexus.flexlink.se/repository/nuget-hosted/ -ApiKey %NUGET_API_KEY%
    only:
        - master
