stages:
    - build
    - upload
    - deploy

#comment
# As default cache policy, cache all untracked files per job and branch (Gradle distributions, Node modules etc)
cache:
    key: "$CI_JOB_NAME $CI_COMMIT_REF_NAME"
    paths:
        - Tools\*

#build:
#    stage: build
#    except:
#        - master
#        - tags
##    tags: 
# #       - visualstudio2017
#    script:
#        - echo CI_COMMIT_REF_NAME='%CI_COMMIT_REF_NAME%'
#        - echo CI_COMMIT_REF_SLUG='%CI_COMMIT_REF_SLUG%'
#        - git describe --tags --abbrev=7 > version.txt
#        - SET /p VERSION=< version.txt
#        - echo Building '%VERSION%' of FLDT
#        #- powershell -File build.ps1 -target=DefaultCi


upload-snapshot:
    stage: build
    only:
        - develop
        - tags
        - branches
    except:
        - master
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags: 
        - visualstudio2017
    script:
        - git describe --tags --abbrev=7 > version.txt
        - SET /p VERSION=< version.txt
        - SET NEXUS_GROUP_ID=com.flexlink.fldt
        - SET NEXUS_ARTIFACT_ID=installation-%CI_COMMIT_REF_SLUG%
        - echo Building '%VERSION%' of FLDT
        - powershell -File build.ps1 -target=DefaultCi
        - echo Uploading FLDT version '%VERSION%' to nexus 'installation snapshots' repository
        - curl -s -u %NEXUS_CREDENTIALS% -X POST http://nexus.flexlink.se/service/rest/v1/components?repository=maven-installation-snapshots -F maven2.groupId=%NEXUS_GROUP_ID% -F maven2.artifactId=%NEXUS_ARTIFACT_ID% -F maven2.version=%VERSION% -F maven2.asset1=@.\build\fldt-installation.msi -F maven2.asset1.extension=msi -F maven2.asset1.classifier=win64 -F maven2.asset2=@.\build\fldt-installation.exe -F maven2.asset2.extension=exe -F maven2.asset2.classifier=win64 -F maven2.asset3=@.\src\Installation\maven\deployment-postfix.bat -F maven2.asset3.extension=bat

upload-release:
    stage: upload
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    except:
        - branches
    tags: 
        - visualstudio2017
    script:
        - git describe --tags --abbrev=7 > version.txt
        - SET /p VERSION=< version.txt
        - SET NEXUS_GROUP_ID=com.flexlink.fldt
        - SET NEXUS_ARTIFACT_ID=installation
        - echo Building '%VERSION%' of FLDT
        - powershell -File build.ps1 -target=DefaultCi
        - echo Uploading FLDT version '%VERSION%' to nexus 'releases' repository
        - curl -s -u %NEXUS_CREDENTIALS% -X POST http://nexus.flexlink.se/service/rest/v1/components?repository=releases -F maven2.groupId=%NEXUS_GROUP_ID% -F maven2.artifactId=%NEXUS_ARTIFACT_ID% -F maven2.version=%VERSION% -F maven2.asset1=@.\build\fldt-installation.msi -F maven2.asset1.extension=msi -F maven2.asset1.classifier=win64 -F maven2.asset2=@.\build\fldt-installation.exe -F maven2.asset2.extension=exe -F maven2.asset2.classifier=win64 -F maven2.asset3=@.\src\Installation\maven\deployment-postfix.bat -F maven2.asset3.extension=bat
